### ISSUE TITLE
[XPMC] Ensure X-platform ZLIB support still operating properly

### ISSUE THREAD

**Issue by bazz1tv** [bazzinotti/XPMCK#19]
Last year, when I was more focused on only getting XPMCK to work on OSX, I made some changes to zlib.e to get ZLIB support working on OSX (8dda967). I want to ensure euphoria interprets and compiles XPMC properly on all platforms even with these changes. If necessary, I can fix any encountered issues.

To properly test it's working, invoke this repo's XPMC by compiling (euc) or interpreting (eui) -- and try to compile an MML to VGZ and play it back. It wouldn't hurt to double check the VGZ is actually a compressed data format and not just a VGM.

@b00daw

**Comment by B00daW** [comment]
@bazz

1.) Compiled lastest XPMC for w32.
2.) Deleted known VGZs in SMS/GG directory.
3.) Compiled SGG VGZ.
4.) Hexedited to verify ZLIB header.
5.) Executed in VGMPlay; no problems. ;)

**Comment by bazz1tv** [comment]
Nice! I have some concern whether certain distributions of Euphoria will compile it, but I think it's safe to close this.
